# --- EXPERIMENT CONFIGURATIONS ---
ATTEMPT_NUM = 0

DEFAULT_SLO = 70
DEFAULT_RTT = 50
DEFAULT_BW = 15
DEFAULT_DATASET = "fmnist"
DEFAULT_SLOWDOWN = 50.0

# Default experiment parameters
DEFAULT_EPOCHS = 20
DEFAULT_BATCH_SIZE = 64
DEFAULT_LR = 0.001
DEFAULT_LAMBDA_LAT = 3.0
DEFAULT_MU = 15.0
