# --- EXPERIMENT CONFIGURATIONS ---
DEFAULT_ATTEMPT_NUM = 0

DEFAULT_SLO = 20
DEFAULT_RTT = 50
DEFAULT_BW = 15
DEFAULT_DATASET = "fmnist"
DEFAULT_SLOWDOWN = 10.0

# Default experiment parameters
DEFAULT_EPOCHS = 20
DEFAULT_BATCH_SIZE = 64
DEFAULT_LR = 0.001
DEFAULT_LAMBDA_LAT = 2.0
DEFAULT_MU = 10.0

# Ablations
SLO_ABLATIONS = [80, 30, 5]  # in ms
NET_ABLATIONS = {"fast": (10, 50), "slow": (150, 5), "impossible": (500, 1)}  # (rtt in ms, bw in Mbps)
DATA_ABLATIONS = ["mnist", "cifar10"]
EDGE_SLOWDOWN_ABLATIONS = [3.0, 30.0, 80.0]